easy_admin:
  site_name: "<b>Admin Panel</b>"
  design:
    brand_color: "green"
    menu:
      - label: "Site"
        icon: "newspaper-o"
        children:
          - { entity: "Categorie", icon: "folder-open", label: "Catégories" }
          - { entity: "Produit", icon: "folder-open", label: "Produits" }
          - { entity: "Commentaire", icon: "folder-open", label: "Commentaires" }
          - { entity: "Contact", icon: "folder-open", label: "Contact" }

      - label: "Accès"
        icon: "user"
        children:
          - { entity: "User", icon: "folder-open", label: "Utilisateurs" }
imports:
  - { resource: admin/ }
