easy_admin:
  entities:
    Categorie:
      class: App\Entity\Categorie
      form:
        fields:
          - { property: "titre", label: "Titre" }

      list:
        actions:
          - { name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary' }
          - { name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger' }

        fields:
          - { property: "titre", label: "Titre" }