easy_admin:
  entities:
    Produit:
      class: App\Entity\Produit
      form:
        fields:
          - { property: "nom", label: "Titre" }
          - { property: "description", label: "Contenu" }
          - { property: "image",label: "Ajouter une image" }
          - { property: "categorie_id", label: "Catégorie" }

      list:
        actions:
          - { name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary' }
          - { name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger' }
          
        fields:
          - { property: "nom", label: "Titre" }
          - { property: "description", label: "Contenu" }
          - { property: "image",label: "Ajouter une image" }
          - { property: "categorie_id", label: "Catégorie" }